apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-ingester
  annotations:
    iam.gke.io/gcp-service-account: 849144245446-compute@developer.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-ingester
  labels:
    app.kubernetes.io/name: ingester
    app.kubernetes.io/part-of: bff
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingester
        app.kubernetes.io/part-of: bff
    spec:
      serviceAccountName: bff-ingester
      containers:
      - name: ingester
        image: ghcr.io/strideynet/bsky-furry-feed/bffsrv:b856f200bfb558f132e03698af7e5757da9605e8
        env:
          - name: ENV
            value: production
        ports:
        - containerPort: 1337
        - containerPort: 1338
        resources:
          requests:
            memory: 500Mi
            cpu: 500m